Algoritmo "repitaAte"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aprendendo como usar o Repita Ate
// Autor(a)    : Filipe Gabriel Rocha
// Data atual  : 11/09/2023
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   repita
      escreval((contador + 1):2, "° ", "Filipe Gabriel Rocha")
      contador <- contador + 1
   ate contador > 9


Fimalgoritmo